"""DAS-GQS: Geometric-equivalent quantum simulation toolkit."""

from .backends import available_backends, get_backend
from .autocompute import (
    ComputePlan,
    HardwareProfile,
    autotune_callable,
    autotune_threads_with_matmul,
    cache_lookup,
    cache_store,
    choose_rotor_kernel,
    default_thread_candidates,
    detect_hardware_profile,
    load_compute_plan_cache,
    make_cache_key,
    parse_thread_candidates,
    profile_as_dict,
    resolve_device,
    save_compute_plan_cache,
)
from .batch_sampling import (
    ChshBatchEstimate,
    EstimateWithCI,
    NoiseRobustnessRow,
    NoiseScenario,
    estimate_chsh_batch,
    noise_robustness_report,
    resolve_batch_sampling_compute_plan,
)
from .core import (
    Bivector,
    EntangledPair,
    G3,
    Pseudoscalar,
    Rotor,
    Scalar,
    Vector,
    generate_rotor,
    geometric_correlation,
    measure_projection,
)

__all__ = [
    "get_backend",
    "available_backends",
    "HardwareProfile",
    "ComputePlan",
    "load_compute_plan_cache",
    "save_compute_plan_cache",
    "make_cache_key",
    "cache_lookup",
    "cache_store",
    "detect_hardware_profile",
    "profile_as_dict",
    "resolve_device",
    "choose_rotor_kernel",
    "default_thread_candidates",
    "parse_thread_candidates",
    "autotune_callable",
    "autotune_threads_with_matmul",
    "Scalar",
    "Vector",
    "Bivector",
    "Pseudoscalar",
    "Rotor",
    "G3",
    "generate_rotor",
    "EntangledPair",
    "measure_projection",
    "geometric_correlation",
    "EstimateWithCI",
    "ChshBatchEstimate",
    "NoiseScenario",
    "NoiseRobustnessRow",
    "estimate_chsh_batch",
    "noise_robustness_report",
    "resolve_batch_sampling_compute_plan",
]
