import json
import os
from colorama import Fore, init

init(autoreset=True)
STATE_FILE = "evo_state.json"

# 这些任务迫使 AI 将内核能力转化为用户可见的 Demo
MANIFESTATION_TASKS = [
    {
        "id": 201,
        "task": "Create 'demo_interactive.py': Build a command-line chat interface that uses 'DiscreteDecisionEngine' to classify user input intent and 'H2QSyntheticEngine' to generate a 'thought trace' response. This is the first User Interface for H2Q.",
        "priority": "critical",
        "status": "pending"
    },
    {
        "id": 202,
        "task": "Implement 'visualize_dream.py': Create a script using matplotlib to visualize the 'Spectral Trace' generated by the Dreaming Mechanism. Plot the eigenvalues of the fractal manifold to show the 'shape' of the AI's thoughts.",
        "priority": "high",
        "status": "pending"
    },
    {
        "id": 203,
        "task": "Build 'H2Q_Server': Create a lightweight FastAPI server in 'tools/api_server.py' that exposes the DDE inference endpoint, allowing external apps to call H2Q capabilities via HTTP.",
        "priority": "medium",
        "status": "pending"
    }
]

def inject():
    if not os.path.exists(STATE_FILE):
        print(f"{Fore.RED}找不到状态文件。")
        return

    with open(STATE_FILE, 'r') as f:
        state = json.load(f)
    
    # 确保 ID 不冲突
    current_ids = [t['id'] for t in state['todo_list']]
    max_id = max(current_ids) if current_ids else 200
    
    print(f"{Fore.CYAN}>>> 正在注入【具象化】任务 (Manifestation Phase)...")
    
    for task in MANIFESTATION_TASKS:
        max_id += 1
        task['id'] = max_id
        # 插入到列表最前面，强制优先执行
        state['todo_list'].insert(0, task)
        print(f"{Fore.GREEN} + [注入] {task['task'][:60]}...")
    
    with open(STATE_FILE, 'w') as f:
        json.dump(state, f, indent=2)
    
    print(f"\n{Fore.MAGENTA}>>> 注入完成！AI 将立即开始构建交互式 Demo。")

if __name__ == "__main__":
    inject()